name: E2E Tests

on: [push]

jobs:
  cypress-run:
    environment: firebase-config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
      - name: Build App
        env:
          REACT_APP_FIREBASE_TEST_CONFIG: "${{ secrets.REACT_APP_FIREBASE_TEST_CONFIG }}"
        run: npm run build:testEnv
      - name: Start server
        env:
          REACT_APP_FIREBASE_TEST_CONFIG: "${{ secrets.REACT_APP_FIREBASE_TEST_CONFIG }}"
        run: npm run start:testEnv &
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          env: 'REACT_APP_FIREBASE_TEST_CONFIG="${{ secrets.REACT_APP_FIREBASE_TEST_CONFIG }}"'
          install: false
          start: echo "started"
          wait-on: "http://localhost:3000"
      - name: Save screenshots on failure
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
