name: E2E Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.5.0-chrome94-ff93
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Insall dependencies
        run: npm i
      - name: Cypress run
        env:
          REACT_APP_FIREBASE_TEST_CONFIG: "${{ secrets.REACT_APP_FIREBASE_TEST_CONFIG }}"
        uses: cypress-io/github-action@v2
        with:
          install: false
          record: false
          browser: chrome
          build: npm run build:testEnv
          start: npm run testEnv
          wait-on: "http://localhost:3000"
          wait-on-timeout: 5000
