name: E2E Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        env:
          REACT_APP_FIREBASE_TEST_CONFIG: "${{ secrets.REACT_APP_FIREBASE_TEST_CONFIG }}"
        uses: cypress-io/github-action@v2
        with:
          build: npm run build:testEnv
          start: npm run testEnv
          wait-on: "http://localhost:3000"
