name: E2E Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
      - name: Build App
        env:
          REACT_APP_FIREBASE_TEST_CONFIG: "${{ secrets.REACT_APP_FIREBASE_TEST_CONFIG }}"
        run: npm run build:testEnv
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          start: npm run start:testEnv
          wait-on: "http://localhost:3000"
          wait-on-timeout: 5000
      - name: Save screenshots on failure
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
